// Auto-generated shader code for directional spreading function normalization factors
// Generated by GenerateSpreadingData.py

#pragma once

// Mitsuyasu normalization Q(s) -- fit in ln(s)/ln(Q) space
// valid range: s in [0.0000, 41844.9343]
// max relative error: low segment 8.51e-04, high segment 2.65e-08
static const float MitsuyasuSplitS = 9517.671321f;
float MitsuyasuNormalizationFactor(float s)
{
    const float lnS = log(s);
    if (s <= MitsuyasuSplitS)
    {
        return exp((((-1.2316466f * lnS + 0.00190119719f) * lnS + 0.48603942f) * lnS + -1.2316466f));
    }
    else
    {
        return exp((((-1.26411493f * lnS + 3.41550215e-05f) * lnS + 0.499623325f) * lnS + -1.26411493f));
    }
}

// Hasselman normalization Q(s) -- fit in ln(s)/ln(Q) space
// valid range: s in [0.0000, 16.1605]
// max relative error: low segment 8.59e-03, high segment 7.48e-05
static const float HasselmanSplitS = 1.204114f;
float HasselmanNormalizationFactor(float s)
{
    const float lnS = log(s);
    if (s <= HasselmanSplitS)
    {
        return exp(((((-1.14439777f * lnS + 0.00553444058f) * lnS + 0.0809236245f) * lnS + 0.404308971f) * lnS + -1.14439777f));
    }
    else
    {
        return exp(((((-1.14496677f * lnS + -0.0101674791f) * lnS + 0.0470321083f) * lnS + 0.387392081f) * lnS + -1.14496677f));
    }
}

