#include "OceanFFT_Common.ush"
/*
    https://github.com/gasgiant/Ocean-URP
    ^ Implementation of GPU FFT I really like, and for which I admire a few key points:
    - Recomputes twiddle factors on the fly, rather than storing them in a texture. This is a performance win because it avoids texture reads and allows for more efficient use of registers.
    - Unrolls the loop so we do everything in a single dispatch
    - parametrizes things like inverting, permute, scaling, etc on uniforms

    However, it uses DIF - meaning that we have to change some logic to use DIT, and we use that because it means we increase our stride
    size used during the butterfly operations incrementally (as powers of 2).... so we can use subgroup ops for many of the early stages
    Fewer barriers, more trying to saturate the GPU with work
*/

#define FFT_USE_WAVE_OPS 0
#define FFT_SIZE_MIN 256
#define FFT_SIZE_REGULAR 512
#define FFT_SIZE_LARGE 1024

#ifndef FFT_SIZE
#define FFT_SIZE FFT_SIZE_REGULAR
#endif

#if FFT_SIZE == FFT_SIZE_MIN
    #define FFT_LOG2_SIZE 8
#elif FFT_SIZE == FFT_SIZE_REGULAR
    #define FFT_LOG2_SIZE 9
#elif FFT_SIZE == FFT_SIZE_LARGE
    #define FFT_LOG2_SIZE 10
#endif

#if COMPILER_SUPPORTS_WAVE_SIZE
	WAVESIZE(32)
    #define FFT_USE_WAVE_OPS 1
#endif

#if FFT_USE_WAVE_OPS
    // WaveSize is only ever guaranteed to be 32, and the UE shader compiler makes sure to set this
    // by default for all platforms as far as I can tell (at least for desktop and console)
    #define FFT_LOG2_WAVE_SIZE 5
#else
    // We use this as our start index for the groupshared fft implementation,
    // so this way the waveops version just means some extra code before the baseline version
    // and a later starting idnex for the groupshared fft implementation, which is a nice way to avoid code duplication
    #define FFT_LOG2_WAVE_SIZE 0
#endif

bool Transpose;
bool Inverse;

// (x,y) : pixel coordinates (z) : cascade
// (each cascade being a different resolution of the FFT, for LOD purposes)
RWTexture2DArray<half4> Target;

// store shared data as half4, to reduce LDS burden (and because the error shouldn't be visible in the heightfield)
groupshared half4 s_SharedDataA[FFT_SIZE];
groupshared half4 s_SharedDataB[FFT_SIZE];

static const float FFT_PI = 3.1415927f;
static const float FFT_2_PI = 6.2831853f;

void ButterflyValues_Radix2(uint stage, uint outputIndex, out uint2 inputIndices, out float2 phaseRotation)
{
    const uint logStep = 1u << stage; // 2^stage
    const uint groupSize = logStep << 1;
    const uint j = outputIndex & (logStep - 1); // outputIndex % logStep
    const uint groupBase = outputIndex & ~(groupSize - 1); // outputIndex with its low bits cleared
    const uint lowerInput = groupBase + j;
    const float theta = -FFT_2_PI / groupSize * j;
    phaseRotation = ComplexExp(theta);
    phaseRotation.y *= -1.0f; // we are always doing the IFFT, so we need to conjugate the phase rotation
    inputIndices = uint2(lowerInput, lowerInput + logStep);
}

half4 DoIFFT_Radix2(in const uint threadIdx, in const half4 input)
{
    const uint bitReversedIdx = reversebits(threadIdx) >> (32 - FFT_LOG2_SIZE);
    s_SharedDataA[bitReversedIdx] = input;
    GroupMemoryBarrierWithGroupSync();

    uint startStage = 0;
    bool pingPong = false;

#if FFT_USE_WAVE_OPS   
    float4 threadData = s_SharedDataA[threadIdx];

    [unroll(5)]
    for (uint stage = 0; stage < FFT_LOG2_WAVE_SIZE; ++stage)
    {
        uint logStep = 1u << stage;
        // compute butterfly values for this stage/thread
        uint2 inputIndices;
        float2 phaseRotation;
        ButterflyValues_Radix2(stage, threadIdx, inputIndices, phaseRotation);
        // grab other data from neighboring thread
        float4 partnerData = WaveReadLaneAt(threadData, WaveGetLaneIndex() ^ logStep);
        const bool isLow = (threadIdx & logStep) == 0;
        float4 a = isLow ? threadData : partnerData;
        float4 b = isLow ? partnerData : threadData;
        float4 rotated = float4(ComplexMul(phaseRotation, b.xy), ComplexMul(phaseRotation, b.zw));

        threadData = isLow ? a + rotated : a - rotated;
    }

    // write wave data back to the LDS
    s_SharedDataA[threadIdx] = half4(threadData);
    GroupMemoryBarrierWithGroupSync();
    startStage = FFT_LOG2_WAVE_SIZE;
#endif

#if FFT_USE_WAVE_OPS
    [unroll(FFT_LOG2_SIZE-FFT_LOG2_WAVE_SIZE)]
#else
    [unroll(FFT_LOG2_SIZE)]
#endif
    for (uint stage = startStage; stage < FFT_LOG2_SIZE; ++stage)
    {
        uint2 inputIndices;
        float2 phaseRotation;
        ButterflyValues_Radix2(stage, threadIdx, inputIndices, phaseRotation);

        float4 a = pingPong ? s_SharedDataB[inputIndices.x] : s_SharedDataA[inputIndices.x];
        float4 b = pingPong ? s_SharedDataB[inputIndices.y] : s_SharedDataA[inputIndices.y];

        float4 rotated = float4(ComplexMul(phaseRotation, b.xy), ComplexMul(phaseRotation, b.zw));
        const bool isLow = (threadIdx & (1u << stage)) == 0;

        if (pingPong)
        {
            s_SharedDataA[threadIdx] = isLow ? half4(a + rotated) : half4(a - rotated);
        }
        else
        {
            s_SharedDataB[threadIdx] = isLow ? half4(a + rotated) : half4(a - rotated);
        }

        pingPong = !pingPong;

        GroupMemoryBarrierWithGroupSync();

    }

    return pingPong ? s_SharedDataB[threadIdx] : s_SharedDataA[threadIdx];
}

// this is dispatched with (1, FFT_SIZE, NumCascades) thread groups, and each thread group
// is responsible for a single column (or row in transpose) of the data
[numthreads(FFT_SIZE, 1, 1)]
void FFT_Radix2_ComputeCS(uint3 dispatchThreadID : SV_DispatchThreadID, uint3 groupID : SV_GroupID)
{
    uint threadIdx = dispatchThreadID.x;
    uint2 targetIndex;
    if (Transpose)
    {
        targetIndex = dispatchThreadID.yx;
    }
    else
    {
        targetIndex = dispatchThreadID.xy;
    }

    // use groupID.z as the cascade index, since we'll dispatch one Z group per cascade
    half4 input = Target[int3(targetIndex, groupID.z)];
    half4 output = DoIFFT_Radix2(threadIdx, input);
    // scale input to recenter it
    half4 scale = half4(1.0f.xxxx - 2.0f.xxxx * half((dispatchThreadID.x + dispatchThreadID.y) % 2).xxxx);
    Target[int3(targetIndex, groupID.z)] = output * scale;
}