// Auto-generated shader code for directional spreading function normalization factors
// Generated by GenerateSpreadingData.py

#pragma once

// Mitsuyasu normalization Q(s) -- fit in ln(s)/ln(Q) space
// valid range: s in [0.0000, 2611117.4963]
// max relative error: low segment 8.14e-04, high segment 1.58e-06
static const float MitsuyasuSplitS = 10239.676456f;
float MitsuyasuNormalizationFactor(in float s)
{
    const float lnS = log(s);
    if (s <= MitsuyasuSplitS)
    {
        return exp(mad(mad(mad(-8.16284866e-05f, lnS, 0.00183001919f), lnS, 0.486468889f), lnS, -1.23247265f));
    }
    else
    {
        return exp(mad(mad(mad(-1.28201575e-07f, lnS, 5.21772775e-06f), lnS, 0.499929208f), lnS, -1.26519176f));
    }
}

// Hasselman normalization Q(s) -- fit in ln(s)/ln(Q) space
// valid range: s in [0.0000, 16.2533]
// max relative error: low segment 8.72e-03, high segment 7.55e-05
static const float HasselmanSplitS = 1.211027f;
float HasselmanNormalizationFactor(in float s)
{
    const float lnS = log(s);
    if (s <= HasselmanSplitS)
    {
        return exp(mad(mad(mad(mad(9.88014667e-06f, lnS, 0.00542962148f), lnS, 0.0805614352f), lnS, 0.403896908f), lnS, -1.14450026f));
    }
    else
    {
        return exp(mad(mad(mad(mad(0.000922057072f, lnS, -0.0101488669f), lnS, 0.0469920358f), lnS, 0.387426512f), lnS, -1.14497632f));
    }
}

float SampleHasselmanLUT(in float beta, in float swell, in Texture2D normTexture, in SamplerState normSampler)
{
    beta = clamp(beta, 8.253544693039466e-07, 1.250472256940183);
    swell = clamp(swell, 0.0, 16.1);
    float u = (beta - 8.253544693039466e-07) / 1.2504714315857137;
    float v = swell / 16.1;
    float result = 0.0f;
    return normTexture.GatherRed(normSampler, float2(u,v)).r
}
