// Auto-generated shader code for directional spreading function normalization factors
// Generated by GenerateSpreadingData.py

#pragma once

// Mitsuyasu normalization Q(s) -- fit in ln(s)/ln(Q) space
// valid range: s in [0.0000, 58464.4228]
// max relative error: low segment 8.56e-04, high segment 5.34e-08
static const float MitsuyasuSplitS = 9629.434343f;
float MitsuyasuNormalizationFactor(float s)
{
    const float lnS = log(s);
    if (s <= MitsuyasuSplitS)
    {
        return exp((((-8.59071413e-05f * lnS + 0.00191200511f) * lnS + 0.48596507f) * lnS + -1.23148887f));
    }
    else
    {
        return exp((((-8.7385731e-07f * lnS + 2.91973899e-05f) * lnS + 0.499672498f) * lnS + -1.26427732f));
    }
}

// Hasselman normalization Q(s) -- fit in ln(s)/ln(Q) space
// valid range: s in [0.0000, 16.1748]
// max relative error: low segment 8.54e-03, high segment 7.49e-05
static const float HasselmanSplitS = 1.205179f;
float HasselmanNormalizationFactor(float s)
{
    const float lnS = log(s);
    if (s <= HasselmanSplitS)
    {
        return exp(((((2.09070239e-05f * lnS + 0.00555033267f) * lnS + 0.0809599815f) * lnS + 0.404317898f) * lnS + -1.1444093f));
    }
    else
    {
        return exp(((((0.000924586257f * lnS + -0.0101646153f) * lnS + 0.0470259548f) * lnS + 0.387397355f) * lnS + -1.14496823f));
    }
}

