#pragma once
#include "OceanFFT_Common.ush"
#include "RandomPCG.ush"


// Spectra texture, z = cascade, xy = (kx, ky)
RWTexture2DArray<half> H0;
RWTexture2DArray<half4> WaveData;

Texture2D<float> HasselmanNormalizationLUT;

uint NoiseSeed;
float WindSpeed; // default 5.0f
float Depth; // default 100.0f
float SwellAmount; // default 0.0f
float Alignment; // default 1.0f
uint DirectionalSpreadingMode; // default OCEAN_FFT_SPREAD_MODE_DONELAN_BANNER
float ThetaOffset; // default 0.0f
float FadeLength;

// cascade parameters
float4 LengthScales;
float4 CutoffsHigh;
float4 CutoffsLow;

static const uint NumWaveCascades = 4;

float4 GetRandomFloat4(in int2 coordinates, in int cascade, in int seed)
{
    int4 pcgInput = int4(coordinates.x, coordinates.y, cascade, seed);
    uint4 pcgResult = Rand4DPCG32(pcgInput);
    return Rand32ToFloat(pcgResult);
}

float2 GetGaussianRandomFloat2(in int2 coordinates, in int cascade, in int seed)
{
    float4 random = GetRandomFloat4(coordinates, cascade, seed);
    float2 gaussianRandom;
    float u1 = max(random.x, 1.0e-7f);
    float u2 = random.y;
    float radius = sqrt(-2.0f * log(u1));
    float theta = OceanFFT_TwoPi * u2;
    return float2(radius * cos(theta), radius * sin(theta));
}

float CascadeContribution(in float k, in uint cascade)
{
    float lengthScale = LengthScales[cascade];
    float cutoffHigh = CutoffsHigh[cascade];
    float cutoffLow = CutoffsLow[cascade];

    if (k < cutoffLow || k > cutoffHigh)
    {
        return 0.0f;
    }
    else
    {
        float total = 0.0f;
        for (uint i = 0; i < NumWaveCascades; ++i)
        {
            bool kInRange = (k >= CutoffsLow[i] && k <= CutoffsHigh[i]);
            if (kInRange)
            {
                total += 1.0f;
            }
        }
        return total;
    }
}


float DirectionalSpreading(
    in float thetaIn,
    in float omega,
    in float peakOmega,
    in float windSpeed,
    in float swellAmount)
{
    float theta = thetaIn - ThetaOffset;
    float spread = 0.0f;
    if BRANCH (DirectionalSpreadingMode == OCEAN_FFT_SPREAD_MODE_MITSUYASU)
    {
        spread = MitsuyasuDirectionalSpread(theta, omega, peakOmega, windSpeed, swellAmount);
    }
    else if BRANCH (DirectionalSpreadingMode == OCEAN_FFT_SPREAD_MODE_HASSELMAN)
    {
        spread = HasselmanDirectionalSpreading(theta, omega, peakOmega, windSpeed, swellAmount);
    }
    else if BRANCH (DirectionalSpreadingMode == OCEAN_FFT_SPREAD_MODE_DONELAN_BANNER)
    {
        spread = DonelanBannerDirectionalSpreading(theta, omega, peakOmega, windSpeed);
    }
    
    // now get into range
    return lerp(0.5f / OceanFFT_Pi, spread, Alignment);
}

float ShortWavesFade(in float kLength, in float fadeLength)
{
    return exp(-fadeLength * fadeLength * kLength * kLength);
}

[numthreads(8, 8, NumWaveCascades)]
void SpectrumInitCS(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    // even though we partition this into workgroups, it's still important to consider coords as global
    int2 coordinates = int2(dispatchThreadID.x - FFT_SIZE / 2, dispatchThreadID.y - FFT_SIZE / 2);
    int cascade = dispatchThreadID.z;
    float dK = OceanFFT_TwoPi / LengthScales[cascade];
    const float2 k = dK * float2(coordinates);
    const float kLength = length(k);

    float contribution = CascadeContribution(kLength, cascade);
    if (contribution > 0.0f)
    {
        const float4 random = GetRandomFloat4(coordinates, cascade, NoiseSeed);
        const float theta = atan2(k.y, k.x);
        float2 omegaAndPeakOmega = DispersionRelationWithDerivative(kLength, Depth);
        
        float directionalComponent = DirectionalSpreading(theta,
                                                          omegaAndPeakOmega.x,
                                                          omegaAndPeakOmega.y,
                                                          WindSpeed,
                                                          SwellAmount);
        
        float freqComponent = OceanEnergySpectrum(WindSpeed,
                                                  Fetch,
                                                  omegaAndPeakOmega.x,
                                                  Depth,
                                                  PeakingFactor);
        
        const float fade = ShortWavesFade(kLength, OceanFFT_ShortWaveFadeLength);
        const float finalSpectrum = freqComponent * directionalComponent * fade;

        WaveData[uint3(dispatchThreadID.xy, cascade)] = half4(k.x,
                                                              finalSpectrum * random.x,
                                                              k.y,
                                                              finalSpectrum * random.y);
    }
    else
    {
        WaveData[uint3(dispatchThreadID.xy, cascade)] = half4(k.x, 0.0f, k.y, 0.0f);
    }

}