#include "OceanFFTCommon.ush"

RWBuffer<float2> ButterflyBuffer;
uint FftDim; // N in the calculations: power of 2
uint Log2FftDim; // log2(N) in the calculations: how many stages we run in the FFT
uint Log2WaveSize; // log2(waveSize) in the calculations: how many stages we run with butterfly vs wave ops
uint WorkgroupCount;

/*
    This is the classic butterfly texture approach, precomputing both the indices and twiddle factors
    for each stage of the FFT. The texture has height of N/2, and width of log2(N)

    This is what almost every ocean FFT implementation uses, but we'll later show how we can use waves
    and subgroup ops to avoid the need for this texture entirely for the first log2(waveSize) stages of the FFT,
    which is a significant performance win.
*/

[numthreads(64,1,1)]
void WriteButterflyBufferCS(uint3 DispatchThreadId : SV_DispatchThreadID,
                            uint3 GroupThreadId : SV_GroupThreadID)
{
    // workgroup count == Log2FftDim, number of stages in the FFT for butterfly ops
    const uint MapSize = WorkgroupCount * 64 * 2; // 2 because we store a complex number and the two indices
    const uint Column = DispatchThreadId.x;
    const uint Stage = DispatchThreadId.y;

    const uint Stride = 1 << Stage;
    const uint HalfStride = MapSize >> (Stage + 1);

    uint Index1 = Column >> Stage;
    uint Index2 = Column % Stride;
    
}