#pragma once
#include "OceanFFT_Generated.hlsl"

// Yes, a complex add or subtract with vector types is just a vector add or subtract, but we define these for clarity
// within the algorithms to make it clear that we're doing complex math, not just vector math
float2 ComplexAdd(float2 a, float2 b)
{
    return a + b;
}

// Same as above: we just want to make it clear that we're doing complex math, not just vector math
float2 ComplexSub(float2 a, float2 b)
{
    return a - b;
}

float2 ComplexExp(float x)
{
    float2 result;
    sincos(x, result.y, result.x);
    return result;
}

float2 ComplexMul(float2 a, float2 b)
{
    // float2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x)
    float2 addend = a.yy * b.yx;
    return fma(a.xx, b, float2(-addend.x, addend.y));
}

float2 ComplexConj(float2 a)
{
    return float2(a.x, -a.y);
}

float2 ComplexDiv(float2 a, float2 b)
{
    float2 denom = 1.0f / dot(b, b);
    return ComplexMul(a, ComplexConj(b)) * denom.xx;
}

/*
Key sources: 
https://dl.acm.org/doi/10.1145/2791261.2791267
https://github.com/blackencino/EncinoWaves/tree/master

Unity implementation:
https://github.com/gasgiant/Ocean-URP/tree/main
Godot implementation:
https://github.com/2Retr0/GodotOceanWaves/tree/main
*/

#define OCEAN_FFT_SPREAD_MODE_MITSUYASU 0
#define OCEAN_FFT_SPREAD_MODE_HASSELMAN 1
#define OCEAN_FFT_SPREAD_MODE_DONELAN_BANNER 2

static const float OceanFFT_Pi = 3.141592653589f;
static const float OceanFFT_TwoPi = 2.0f * OceanFFT_Pi;
static const float OceanFFT_G = 9.81f;
static const float OceanFFT_SigmaOverRho = 0.074e-3f; // Surface tension over water density


float GetDimensionlessFetch(in float fetch, in float windSpeed)
{
    // 1000.0f = 1km in meters, and we divide by windSpeed^2 to get a dimensionless number
    return abs((fetch * 1000.0f * OceanFFT_G) / (windSpeed * windSpeed));
}

float GetJonswapAlpha(in float dimensionlessFetch)
{
    return 0.076f * pow(dimensionlessFetch, -0.22f);
}

float GetJonswapPeakOmega(in float dimensionlessFetch, in float windSpeed)
{
    return OceanFFT_TwoPi * 3.50f * abs(OceanFFT_G / windSpeed) * pow(dimensionlessFetch, -0.33f);
}

// peak sharpening is gamma raised to this value
// todo: is this actually the right formulation of this value? it differs from references, but follows paper...
float GetPeakSharpeningPower(in float omega, in float peakOmega)
{
    float sigma = (omega <= peakOmega) ? 2.0f * (0.07f * 0.07f) : 2.0f * (0.09f * 0.09f);
    const float numerator = (omega - peakOmega) * (omega - peakOmega);
    const float denominator = sigma * (peakOmega * peakOmega);
    return exp(-(numerator / denominator));
}

float KitaiGorodskiiDepthCorrection(in float omega, in float depth)
{
    // graphed smoothstep vs the piecewise, and despite the Horvath paper suggesting that 0-2.2 is the right interval, we actaully get 
    // a tighter fit with 0-2.0. I think the piecewise is still the tightest fit we could get without implementing the full correction
    // (which isn't happening), but this is a good compromise and is nice and branchless and still clamped
    // bizarrely, horvath's own tanh approximation is actually a worse fit than all of the alternatives. i think he chose it for boundary
    // condition handling happening gracefully
    const float omegaH = omega * sqrt(depth / OceanFFT_G);
    return smoothstep(0.0f, 2.0f, omegaH);
}

// all ocean spectra are some form of alpha-beta spectrum, so I'm implementing this here to try and shove it into my brain 
float AlphaBetaSpectrum(in float A, in float B, in float omega, in float peakOmega)
{
    const float omegaTerm = omega * omega * omega * omega * omega;
    const float alphaTerm = (A * (OceanFFT_G * OceanFFT_G)) / omegaTerm;
    const float peakOmegaOverOmega = peakOmega / omega;
    const float peakOmegaTerm = peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega;
    const float betaTerm = exp(-B * peakOmegaTerm);
    return alphaTerm * betaTerm;
}

/**
windSpeed: wind speed at 10m in m/s
fetch: distance over which the wind blows in km (km!)
omega:
depth: depth of the water in meters
gamma: peak sharpening factor, default 3.3 (for now)

returns the energy spectrum, based on Jonswap with depth correction.
needs to be multiplied by the directional spectrum component
*/
float OceanEnergySpectrum(in float windSpeed, in float fetch, in float omega, in float depth, in float gamma)
{
    const float dimensionlessFetch = min(GetDimensionlessFetch(windSpeed, fetch), 1e6f);
    const float alpha = GetJonswapAlpha(dimensionlessFetch);
    const float peakOmega = GetJonswapPeakOmega(dimensionlessFetch, windSpeed);
    const float peakSharpeningPower = GetPeakSharpeningPower(omega, peakOmega);
    const float peakSharpening = pow(gamma, peakSharpeningPower);
    static const float jonswapBeta = 1.25f;
    const float baseSpectrum = AlphaBetaSpectrum(alpha, jonswapBeta, omega, peakOmega);
    const float correction = KitaiGorodskiiDepthCorrection(omega, depth);
    return peakSharpening * (correction * baseSpectrum);
}

// When depth is much much greater than wavelength, dispersion relation is w^2 = g*k.
// When depth is much much less than wavelength, dispersion relation is w^2 = gktanh(kh).
// For capillary waves, the dispersion relation is w^2 = gk + (T/rho)k^3, where T is surface tension
// and rho is water density.
// Like the reference paper, we use the capillary formation as k is inversely proportional to wavelength,
// so for small wavelengths (high k) the capillary term dominates: for swells, it is negligible.
// Dispersion is our spatial frequency (w) as a function of wave number (k) and depth (h)
float DispersionRelation(in float kLength, in float depth)
{
    const float capillaryTerm = OceanFFT_SigmaOverRho * kLength * kLength * kLength;
    const float gravityTerm = OceanFFT_G * kLength;
    const float depthTerm = tanh(min(kLength * depth, 10.0f));
    return sqrt((gravityTerm + capillaryTerm) * depthTerm);
}

// Calculates the dispersion relation and it's derivative with respect to k, in one operation
// since we only ever use these together (during initial spectrum computation)
float2 DispersionRelationWithDerivative(in float kLength, in float depth)
{
    float2 result = float2(0.0f, 0.0f);
    const float capillaryTerm = OceanFFT_SigmaOverRho * kLength * kLength;
    const float capillaryPlusGravityTerm = OceanFFT_G + capillaryTerm;
    const float depthTerm = tanh(min(kLength * depth, 10.0f));
    result.x = sqrt(abs(kLength * capillaryPlusGravityTerm * depthTerm));
    // now get derivative. based on horvath paper and his notes
    // pre-invert so we can multiply instead of divide
    const float coshTerm = cosh(min(kLength * depth, 10.0f));
    const float sechTerm = 1.0f / (coshTerm * coshTerm);
    const float numeratorPart1 = (capillaryPlusGravityTerm + capillaryTerm + capillaryTerm) * depthTerm;
    const float numeratorPart2 = (min(kLength * depth, 10.0f) * capillaryPlusGravityTerm) * sechTerm;
    result.y = abs(numeratorPart1 + numeratorPart2) / (2.0f * result.x);
    return result;
}

float DonelanBannerBeta(in float omega, in float peakOmega)
{
    // Watching occupancy and VGPRs get bigger the more of this we implement.... sad
    const float omegaOverPeakOmega = omega / peakOmega;
    if (omegaOverPeakOmega < 0.95f)
    {
        return 2.61f * pow(omegaOverPeakOmega, 1.3f);
    }
    else if (omegaOverPeakOmega < 1.60f)
    {
        return 2.28f * pow(omegaOverPeakOmega, -1.3f);
    }
    else
    {
        const float exponent = -0.4f + 0.8393f * exp(-0.567f * log(omegaOverPeakOmega * omegaOverPeakOmega));
        return pow(10.0f, exponent);
    }
}

float SwellShaper(in float omega, in float peakOmega, in float swellAmount)
{
    const float peakOmegaOverOmega = peakOmega / omega;
    return 16.1f * tanh(peakOmegaOverOmega) * (swellAmount * swellAmount);
}

float SwellDirectionalSpreading(in float theta, in float omega, in float peakOmega, in float swellAmount)
{
    const float swell = 2.0f * SwellShaper(omega, peakOmega, swellAmount);
    const float spread = abs(cos(theta * 0.5f));
    return pow(spread, swell);
}

float SpreadPowerMitsuyasu(in float omega, in float peakOmega, in float windSpeed)
{
    const float x = (peakOmega * windSpeed) / OceanFFT_G;
    const float xPow = pow(x, -2.5f);
    return 11.5f * xPow;
}

float SpreadPowerHasselman(in float omega, in float peakOmega, in float windSpeed)
{
    const float windOverModalCelerity = windSpeed / (OceanFFT_G / peakOmega);
    float shape = 0.0f;
    if (omega > peakOmega)
    {
        // what the hell
        shape = 9.77f * pow(omega / peakOmega, -2.33f - (1.45f * (windOverModalCelerity - 1.17f)));
    }
    else
    {
        shape = 6.97f * pow(omega / peakOmega, 4.06f);
    }
    return shape;
}

float PositiveCosineSquaredDirectionalSpreading(in float theta, in float spreadPower)
{
    const float cosTheta = abs(cos(theta * 0.5f));
    return pow(cosTheta, 2.0f * spreadPower);
}

float MitsuyasuDirectionalSpread(
    in float theta,
    in float omega,
    in float peakOmega,
    in float windSpeed,
    in float swellAmount)
{
    const float spreadPower = SpreadPowerMitsuyasu(omega, peakOmega, windSpeed);
    const float norm = MitsuyasuNormalizationFactor(spreadPower);
    const float swell = SwellDirectionalSpreading(theta, omega, peakOmega, swellAmount);
    const float spread = PositiveCosineSquaredDirectionalSpreading(theta, spreadPower);
    return PositiveCosineSquaredDirectionalSpreading(theta, spread + swell) * norm;
}

float HasselmanDirectionalSpreading(
    in float theta,
    in float omega,
    in float peakOmega,
    in float windSpeed,
    in float swellAmount)
{
    const float spreadPower = SpreadPowerHasselman(omega, peakOmega, windSpeed);
    const float norm = HasselmanNormalizationFactor(spreadPower);
    const float swell = SwellDirectionalSpreading(theta, omega, peakOmega, swellAmount);
    return PositiveCosineSquaredDirectionalSpreading(theta, spreadPower + swell) * norm;
}

// closed form of Donelan-Banner directional spreading. d/dTheta[tanh(beta * theta)] = beta * sech^2(beta * theta)
// for our normalization, we need to integrate this over the unit circle and divide by the integral to normalize it.
// integral goes from -pi to pi (the unit circle), so using fundamental theorem of calculus we know we can just do
// 1 / beta * (tanh(beta * pi) - tanh(-beta * pi)) = 2 / beta * tanh(beta * pi)
// (because tanh is odd, so tanh(-x) = -tanh(x))
// neat!
float DonelanBannerDirectionalSpreading(
    in float theta,
    in float omega,
    in float peakOmega,
    in float swellAmount,
    in SamplerState normSampler,
    in Texture2D normTexture)
{
    const float beta = DonelanBannerBeta(omega, peakOmega);                              // u axis
    const float swell = SwellDirectionalSpreading(theta, omega, peakOmega, swellAmount); // v axis
    // we pre-divide before storing to the lut, so we can just mul by this
    const float norm = SampleHasselmanLUT(beta, swell, normTexture, normSampler);
    const float db = 1.0f / cosh(theta * beta);
    const float db2 = db * db;
    return (db2 * swell) * norm;
}